#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

DOCKER_POOL_CONF="/etc/php5/fpm/pool.d/openmediavault-docker-site.conf"
DOCKER_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-docker-site.conf"

case "$1" in
    purge|remove)

        if [ -e "${DOCKER_SITE_CONF}" ]; then
            rm -f ${DOCKER_SITE_CONF}
        fi

        if [ -e "${DOCKER_POOL_CONF}" ]; then
            rm -f ${DOCKER_POOL_CONF}
        fi
			
	apt-get remove docker

        service php5-fpm reload
        service nginx reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
